extends: default

rules:
  # don't bother me with this rule
  # indentation: disable
  line-length: disable
  indentation: disable
  empty-lines: disable
  braces: disable
  colons: disable
  commas: disable
  hyphens: disable
  brackets: disable
  new-line-at-end-of-file: disable
  new-lines: disable
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - '*.rul'