extends: default

rules:
  # don't bother me with these rules
  line-length: disable
  document-start: disable
  # don't bother as there is no huge benefit
  comments: disable
  # comments:
  #   spaces: 1  # breaks yamllint
  #   level: error
  # don't bother as there is no huge benefit
  comments-indentation: disable
  # comments-indentation:
  #   level: error
  new-line-at-end-of-file: disable
  new-lines: disable
  empty-lines: disable

  indentation:
    spaces: 2
    indent-sequences: true  # create false positives  # false create even more issues
    check-multi-line-strings: false  # breaks scripts
  truthy:
    level: error
  braces: enable
  colons: enable
  commas: enable
  hyphens: enable
  brackets: enable

yaml-files:
  - '*.yaml'
  # - '*.yml'
  - '.yamllint'
  - '*.rul'
  - '*.nam'