extends: default

rules:
  # don't bother me with this rule
  line-length: disable
  document-start: disable

  indentation: disable
  # indentation:
  #   spaces: 2
  #   indent-sequences: true  # create false positives  # false create even more issues
  #   check-multi-line-strings: false  # breaks scripts
  comments:
    level: error
    # spaces: 1  # breaks yamllint
  # comments-indentation:
  #   level: error
  truthy:
    level: error
  empty-lines: disable
  braces: disable
  colons: disable
  commas: disable
  # hyphens: disable
  brackets: disable
  new-line-at-end-of-file: disable
  new-lines: disable
yaml-files:
  - '*.yaml'
#  - '*.yml'
  - '.yamllint'
  - '*.rul'
  - '*.nam'