extends: default

rules:
  # don't bother me with this rule
  line-length: disable
  document-start: disable

  indentation: disable
  # indentation:
  #   spaces: 2
  #   indent-sequences: true
  #   check-multi-line-strings: false  # breaks scripts
  comments:
    level: error
  # comments-indentation:
  #   level: error
  empty-lines: disable
  braces: disable
  colons: disable
  commas: disable
  # hyphens: disable
  brackets: disable
  new-line-at-end-of-file: disable
  new-lines: disable
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - '*.rul'
  - '*.nam'