name: Validate YAML with Yamllint

on:  # yamllint disable-line rule:truthy
  pull_request:  # yamllint disable-line rule:empty-values

jobs:
  lint:
    runs-on: codeberg-tiny

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v3

      # Step 2: Set up Python and install yamllint
      - name: Set up Python and Install Yamllint
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Yamllint
        run: |
          pip3 install yamllint

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      # Step 3: Run yamllint on all YAML files
      - name: Lint YAML files
        run: |
          echo "Start Linting"
          RETURN_CODE=0
          for file in ${{ steps.changed-files.outputs.all_changed_files }};
          do
            echo "Linting $file"
            yamllint --no-warnings -c ./.yamllint.yml $file
            if [ $? -ne 0 ]; then  # check if return code fails at least once in the for loop
              RETURN_CODE=1
            fi
          done
          if [ $RETURN_CODE -ne 0 ]; then
            echo "Linting failed"
            false  # fail workflow step
          else
            echo "Linting done"
            true
          fi