name: Validate YAML with Yamllint

on:  # yamllint disable-line rule:truthy
  pull_request:  # yamllint disable-line rule:empty-values

jobs:
  lint:
    runs-on: codeberg-tiny

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v3

      ## Step 2 - ghcr.io/catthehacker/ubuntu:act-latest should have it already
      #- name: Set up Python
      #  uses: https://code.forgejo.org/actions/setup-python@v5

      - name: Install Yamllint
        run: |
          pip3 install yamllint

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ","
          files: |
            **/*.rul
            **/*.yml
            **/*.yaml

      # Step 3: Run yamllint on all YAML files
      - name: Lint YAML files
        run: |
          echo "Start Linting"
          RETURN_CODE=0
          IFS=$',' read -a MODIFIED_FILES_ARRAY <<< "${{ steps.changed-files-comma.outputs.modified_files }}"
          for file in "${MODIFIED_FILES_ARRAY[@]}";
          do
            echo "Linting $file"
            if yamllint --no-warnings -c ./.yamllint.yml "$file"; then
              : # nop on success (return code == 0)
            else
              RETURN_CODE=1
            fi
          done
          if [ $RETURN_CODE -ne 0 ]; then
            echo "Linting failed"
            false  # fail workflow step
          else
            echo "Linting done"
            true
          fi