name: Validate YAML with check_jsonschema

on:  # yamllint disable-line rule:truthy
  pull_request:  # yamllint disable-line rule:empty-values

jobs:
  yaml_validator:
    runs-on: codeberg-tiny

    steps:
      # Step 1
      - name: Check out code
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v3

      # Step 2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3
      - name: Install check-jsonschema and Dependencies
        run: |
          pip3 install check-jsonschema
          npm install json-merger

      # Step 4
      - name: Prepare files for check_jsonschema  # probably should be cached?
        run: |
          git clone https://github.com/OpenXcom/vscode-ruleset
          cp ./helpers/workflow_yaml_schema_validator/merger.js ./vscode-ruleset/schemas/oxce-merge
          cd ./vscode-ruleset/schemas/oxce-merge
          node merger.js
          cd -
          cp ./vscode-ruleset/schemas/oxce-merge/* ./vscode-ruleset/schemas/oxc


      # Step 5
      - name: Prepare ROSIGMA dir
        run: |
          echo 'Removing !add, !remove, !seq constructors as check_jsonschema cannot handle them'
          find . -name "*.rul" | xargs -I {} sed -i 's/\!\(add\|remove\|seq\)//g' {}

      # Step 6
      - name: Run check_jsonschema
        run: |
          cd ./vscode-ruleset/schemas/oxc
          SCHEMA_PATH=$(pwd)
          cd -
          echo "Schema Path is:"
          echo $SCHEMA_PATH
          find . -name "*.rul" | xargs -I {} check-jsonschema --schemafile $SCHEMA_PATH/ruleset.json --default-filetype yaml --base-uri "file://$SCHEMA_PATH/" {}
          echo "Validation done"